/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ElementJsonFile {
  getUri(): Uri
  getReference(): Array<ElementJsonFileReference>
}

export declare class ElementJsonFileReference {
  getNameStart(): number
  getNameEnd(): number
  getValueStart(): number
  getValueEnd(): number
  getNameText(): string
  getValueText(): string
}

export declare class ProjectDetector {
  static create(workspaceFolder: string): ProjectDetector
  static create(workspaceFolder: string): ProjectDetector
  getWorkspaceFolder(): Uri
}

export declare class Uri {
  static file(path: string): Uri
  static parse(url: string): Uri
  get fsPath(): string
  get path(): string
  get scheme(): string
  get host(): string
  get query(): string
  get fragment(): string
  get username(): string
  get password(): string
  get port(): number
  toString(): string
}
