[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.wasm32-wasip1-threads]
linker = "clang"
rustflags = [
  "-C", "link-arg=--target=wasm32-wasip1-threads",
  "-C", "link-arg=--sysroot=${WASI_SDK_PATH}/share/wasi-sysroot",
]