on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm environment & install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Install napi command line tool
        run: pnpm i -g @napi-rs/cli

      - name: Setup rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt,clippy

      - name: Lint
        run: cargo clippy && pnpm eslint

      - name: Build
        run: pnpm build

      - name: Run rust tests
        run: cargo test

      - name: Run vitest
        run: pnpm test --coverage
